name: Publish docker images in github
run-name: "Publish docker images in github @${{github.actor}}, event:${{github.event_name}}"
on:
  release:
    types: [published]

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Test cred
        run: |
          echo "username: ${{ secrets.DOCKERHUB_USERNAME }}"
          echo "password: ${{ secrets.DOCKERHUB_PASSWD }}"
      - name: Login in docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: gbigbi210141989/node-js-api-web-app
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build & Publish Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
        
        